#热修复
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
#
#spring.devtools.restart.exclude=

#格式化日期
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  datasource:
    url: jdbc:mysql://localhost:3306/DataNeu?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    #url: jdbc:mysql://192.168.3.4:3306/DataHhlt?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    #url: jdbc:mysql://localhost:3306/DataNeu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#JPA
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
